cask_args appdir: "/Applications"
tap "caskroom/cask"
tap "ggpeti/rmrec"
tap "homebrew/bundle"
tap "homebrew/core"
tap "homebrew/services"
brew "autogen"
brew "automake"
brew "awscli"
brew "awslogs"
brew "bash-completion"
brew "bash-git-prompt"
brew "cloc"
brew "cmake"
brew "cscope"
brew "ctags"
brew "docker-completion"
brew "dockutil"
brew "duti"
brew "figlet"
brew "flake8"
brew "git"
brew "git-extras"
brew "git-quick-stats"
brew "go"
brew "hadolint"
brew "heroku"
brew "httpie"
brew "jq"
brew "jsonlint"
brew "libtool"
brew "libyaml"
brew "lua"
brew "luajit"
brew "macvim", args: ["with-lua", "with-luajit", "with-override-system-vim", "with-python3"]
brew "mas"
brew "nasm"
brew "node"
brew "nvm"
brew "pngcrush"
brew "pup"
brew "python3"
brew "rbenv"
brew "rbenv-binstubs"
brew "recode"
brew "rust"
brew "svgo"
brew "switchaudio-osx"
brew "the_platinum_searcher"
brew "tidy-html5"
brew "tree"
brew "unrar"
brew "wabt"
brew "watch"
brew "wget"
brew "yarn"
brew "z"
cask "google-chrome"
cask "otx"
cask "skyfonts"
cask "sourcetree"
mas "Airmail 3", id: 918858936
mas "CCMenu", id: 603117688
mas "Fantastical 2", id: 975937182
mas "Keynote", id: 409183694
mas "Logic Pro X", id: 634148309
mas "Pixelmator", id: 407963104
mas "Slack", id: 803453959
mas "SoundCloud", id: 412754595
mas "Things3", id: 904280696
mas "Tweetbot", id: 557168941
mas "Xcode", id: 497799835
