#!/usr/bin/env bash

# shellcheck disable=SC2016,SC2155

# make direnv silent by default
export DIRENV_LOG_FORMAT=""

layout_poetry() {
  if [[ ! -f pyproject.toml ]]; then
    log_error 'No pyproject.toml found.  Use `poetry new` or `poetry init` to create one first.'
    exit 2
  fi

  local VENV=$(dirname "$(poetry run which python)")
  export VIRTUAL_ENV=$(echo "$VENV" | rev | cut -d'/' -f2- | rev)
  export POETRY_ACTIVE=1
  PATH_add "$VENV"
}

layout_uv() {
  local UV
  UV=$(which uv || true)
  if [ -z "$UV" ]; then
    log_error "bin \`uv\` not found"
    return 1
  fi

  export UV_PROJECT_ENVIRONMENT="$PWD/.venv"
  PATH_add "$UV_PROJECT_ENVIRONMENT/bin"

  if [ ! -d ".venv" ]; then
    uv venv
  fi

  if [ -f "pyproject.toml" ]; then
    uv sync
  fi
}

